/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "aa_authority.h"

gboolean
aa_authority_if_aasetup (aaAuthorityIf *iface, aaAuthParamter ** _return, const GByteArray * pub, const GPtrArray * attributes, const gchar * aid, GError **error)
{
  return AA_AUTHORITY_IF_GET_INTERFACE (iface)->aasetup (iface, _return, pub, attributes, aid, error);
}

gboolean
aa_authority_if_aakeygen (aaAuthorityIf *iface, aaARevoKey ** _return, const aaAuthParamter * auth, const GByteArray * pub, const GByteArray * cert, const GPtrArray * attribtues, GError **error)
{
  return AA_AUTHORITY_IF_GET_INTERFACE (iface)->aakeygen (iface, _return, auth, pub, cert, attribtues, error);
}

gboolean
aa_authority_if_updatekey (aaAuthorityIf *iface, aaAttrPair ** _return, const GByteArray * auth_msk, const GByteArray * pub, const GByteArray * attr_pk, const GByteArray * attr_msk, const gchar * attribute, GError **error)
{
  return AA_AUTHORITY_IF_GET_INTERFACE (iface)->updatekey (iface, _return, auth_msk, pub, attr_pk, attr_msk, attribute, error);
}

GType
aa_authority_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (aaAuthorityIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "aaAuthorityIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
aa_authority_if_interface_init (aaAuthorityIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (aaAuthorityClient, aa_authority_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (AA_TYPE_AUTHORITY_IF,
                                                aa_authority_if_interface_init))

enum _aaAuthorityClientProperties
{
  PROP_0,
  PROP_AA_AUTHORITY_CLIENT_INPUT_PROTOCOL,
  PROP_AA_AUTHORITY_CLIENT_OUTPUT_PROTOCOL
};

void
aa_authority_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  aaAuthorityClient *client = AA_AUTHORITY_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_AA_AUTHORITY_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_AA_AUTHORITY_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
aa_authority_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  aaAuthorityClient *client = AA_AUTHORITY_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_AA_AUTHORITY_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_AA_AUTHORITY_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean aa_authority_client_send_aasetup (aaAuthorityIf * iface, const GByteArray * pub, const GPtrArray * attributes, const gchar * aid, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = AA_AUTHORITY_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "aasetup", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "aasetup_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "pub", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, pub ? ((GByteArray *) pub)->data : NULL, pub ? ((GByteArray *) pub)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "attributes", T_LIST, 2, error)) < 0)
      return 0;
    xfer += ret;
    {
      guint i20;

      if ((ret = thrift_protocol_write_list_begin (protocol, T_STRING, (gint32) (attributes ? attributes->len : 0), error)) < 0)
        return 0;
      xfer += ret;
      for (i20 = 0; i20 < (attributes ? attributes->len : 0); i20++)
      {
        if ((ret = thrift_protocol_write_string (protocol, ((gchar*)g_ptr_array_index ((GPtrArray *) attributes, i20)), error)) < 0)
          return 0;
        xfer += ret;

      }
      if ((ret = thrift_protocol_write_list_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "aid", T_STRING, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, aid, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean aa_authority_client_recv_aasetup (aaAuthorityIf * iface, aaAuthParamter ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = AA_AUTHORITY_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "aasetup", 7) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected aasetup", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean aa_authority_client_aasetup (aaAuthorityIf * iface, aaAuthParamter ** _return, const GByteArray * pub, const GPtrArray * attributes, const gchar * aid, GError ** error)
{
  if (!aa_authority_client_send_aasetup (iface, pub, attributes, aid, error))
    return FALSE;
  if (!aa_authority_client_recv_aasetup (iface, _return, error))
    return FALSE;
  return TRUE;
}

gboolean aa_authority_client_send_aakeygen (aaAuthorityIf * iface, const aaAuthParamter * auth, const GByteArray * pub, const GByteArray * cert, const GPtrArray * attribtues, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = AA_AUTHORITY_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "aakeygen", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "aakeygen_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "auth", T_STRUCT, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (auth), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "pub", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, pub ? ((GByteArray *) pub)->data : NULL, pub ? ((GByteArray *) pub)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "cert", T_STRING, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, cert ? ((GByteArray *) cert)->data : NULL, cert ? ((GByteArray *) cert)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "attribtues", T_LIST, 4, error)) < 0)
      return 0;
    xfer += ret;
    {
      guint i21;

      if ((ret = thrift_protocol_write_list_begin (protocol, T_STRING, (gint32) (attribtues ? attribtues->len : 0), error)) < 0)
        return 0;
      xfer += ret;
      for (i21 = 0; i21 < (attribtues ? attribtues->len : 0); i21++)
      {
        if ((ret = thrift_protocol_write_string (protocol, ((gchar*)g_ptr_array_index ((GPtrArray *) attribtues, i21)), error)) < 0)
          return 0;
        xfer += ret;

      }
      if ((ret = thrift_protocol_write_list_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean aa_authority_client_recv_aakeygen (aaAuthorityIf * iface, aaARevoKey ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = AA_AUTHORITY_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "aakeygen", 8) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected aakeygen", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean aa_authority_client_aakeygen (aaAuthorityIf * iface, aaARevoKey ** _return, const aaAuthParamter * auth, const GByteArray * pub, const GByteArray * cert, const GPtrArray * attribtues, GError ** error)
{
  if (!aa_authority_client_send_aakeygen (iface, auth, pub, cert, attribtues, error))
    return FALSE;
  if (!aa_authority_client_recv_aakeygen (iface, _return, error))
    return FALSE;
  return TRUE;
}

gboolean aa_authority_client_send_updatekey (aaAuthorityIf * iface, const GByteArray * auth_msk, const GByteArray * pub, const GByteArray * attr_pk, const GByteArray * attr_msk, const gchar * attribute, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = AA_AUTHORITY_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "updatekey", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "updatekey_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "auth_msk", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, auth_msk ? ((GByteArray *) auth_msk)->data : NULL, auth_msk ? ((GByteArray *) auth_msk)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "pub", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, pub ? ((GByteArray *) pub)->data : NULL, pub ? ((GByteArray *) pub)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "attr_pk", T_STRING, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, attr_pk ? ((GByteArray *) attr_pk)->data : NULL, attr_pk ? ((GByteArray *) attr_pk)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "attr_msk", T_STRING, 4, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, attr_msk ? ((GByteArray *) attr_msk)->data : NULL, attr_msk ? ((GByteArray *) attr_msk)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "attribute", T_STRING, 5, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, attribute, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean aa_authority_client_recv_updatekey (aaAuthorityIf * iface, aaAttrPair ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = AA_AUTHORITY_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "updatekey", 9) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected updatekey", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean aa_authority_client_updatekey (aaAuthorityIf * iface, aaAttrPair ** _return, const GByteArray * auth_msk, const GByteArray * pub, const GByteArray * attr_pk, const GByteArray * attr_msk, const gchar * attribute, GError ** error)
{
  if (!aa_authority_client_send_updatekey (iface, auth_msk, pub, attr_pk, attr_msk, attribute, error))
    return FALSE;
  if (!aa_authority_client_recv_updatekey (iface, _return, error))
    return FALSE;
  return TRUE;
}

static void
aa_authority_if_interface_init (aaAuthorityIfInterface *iface)
{
  iface->aasetup = aa_authority_client_aasetup;
  iface->aakeygen = aa_authority_client_aakeygen;
  iface->updatekey = aa_authority_client_updatekey;
}

static void
aa_authority_client_init (aaAuthorityClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
aa_authority_client_class_init (aaAuthorityClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = aa_authority_client_set_property;
  gobject_class->get_property = aa_authority_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_AA_AUTHORITY_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_AA_AUTHORITY_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
aa_authority_handler_authority_if_interface_init (aaAuthorityIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (aaAuthorityHandler, 
                         aa_authority_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (AA_TYPE_AUTHORITY_IF,
                                                aa_authority_handler_authority_if_interface_init))

gboolean aa_authority_handler_aasetup (aaAuthorityIf * iface, aaAuthParamter ** _return, const GByteArray * pub, const GPtrArray * attributes, const gchar * aid, GError ** error)
{
  g_return_val_if_fail (AA_IS_AUTHORITY_HANDLER (iface), FALSE);

  return AA_AUTHORITY_HANDLER_GET_CLASS (iface)->aasetup (iface, _return, pub, attributes, aid, error);
}

gboolean aa_authority_handler_aakeygen (aaAuthorityIf * iface, aaARevoKey ** _return, const aaAuthParamter * auth, const GByteArray * pub, const GByteArray * cert, const GPtrArray * attribtues, GError ** error)
{
  g_return_val_if_fail (AA_IS_AUTHORITY_HANDLER (iface), FALSE);

  return AA_AUTHORITY_HANDLER_GET_CLASS (iface)->aakeygen (iface, _return, auth, pub, cert, attribtues, error);
}

gboolean aa_authority_handler_updatekey (aaAuthorityIf * iface, aaAttrPair ** _return, const GByteArray * auth_msk, const GByteArray * pub, const GByteArray * attr_pk, const GByteArray * attr_msk, const gchar * attribute, GError ** error)
{
  g_return_val_if_fail (AA_IS_AUTHORITY_HANDLER (iface), FALSE);

  return AA_AUTHORITY_HANDLER_GET_CLASS (iface)->updatekey (iface, _return, auth_msk, pub, attr_pk, attr_msk, attribute, error);
}

static void
aa_authority_handler_authority_if_interface_init (aaAuthorityIfInterface *iface)
{
  iface->aasetup = aa_authority_handler_aasetup;
  iface->aakeygen = aa_authority_handler_aakeygen;
  iface->updatekey = aa_authority_handler_updatekey;
}

static void
aa_authority_handler_init (aaAuthorityHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
aa_authority_handler_class_init (aaAuthorityHandlerClass *cls)
{
  cls->aasetup = NULL;
  cls->aakeygen = NULL;
  cls->updatekey = NULL;
}

enum _aaAuthorityProcessorProperties
{
  PROP_AA_AUTHORITY_PROCESSOR_0,
  PROP_AA_AUTHORITY_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (aaAuthorityProcessor,
               aa_authority_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* aaAuthorityProcessorProcessFunction) (aaAuthorityProcessor *, 
                                                          gint32,
                                                          ThriftProtocol *,
                                                          ThriftProtocol *,
                                                          GError **);

typedef struct
{
  gchar *name;
  aaAuthorityProcessorProcessFunction function;
} aa_authority_processor_process_function_def;

static gboolean
aa_authority_processor_process_aasetup (aaAuthorityProcessor *,
                                        gint32,
                                        ThriftProtocol *,
                                        ThriftProtocol *,
                                        GError **);
static gboolean
aa_authority_processor_process_aakeygen (aaAuthorityProcessor *,
                                         gint32,
                                         ThriftProtocol *,
                                         ThriftProtocol *,
                                         GError **);
static gboolean
aa_authority_processor_process_updatekey (aaAuthorityProcessor *,
                                          gint32,
                                          ThriftProtocol *,
                                          ThriftProtocol *,
                                          GError **);

static aa_authority_processor_process_function_def
aa_authority_processor_process_function_defs[3] = {
  {
    "aasetup",
    aa_authority_processor_process_aasetup
  },
  {
    "aakeygen",
    aa_authority_processor_process_aakeygen
  },
  {
    "updatekey",
    aa_authority_processor_process_updatekey
  }
};

static gboolean
aa_authority_processor_process_aasetup (aaAuthorityProcessor *self,
                                        gint32 sequence_id,
                                        ThriftProtocol *input_protocol,
                                        ThriftProtocol *output_protocol,
                                        GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  aaAuthorityAasetupArgs * args =
    g_object_new (AA_TYPE_AUTHORITY_AASETUP_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * pub;
    GPtrArray * attributes;
    gchar * aid;
    aaAuthParamter * return_value;
    aaAuthorityAasetupResult * result_struct;

    g_object_get (args,
                  "pub", &pub,
                  "attributes", &attributes,
                  "aid", &aid,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (AA_TYPE_AUTHORITY_AASETUP_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (aa_authority_handler_aasetup (AA_AUTHORITY_IF (self->handler),
                                      &return_value,
                                      pub,
                                      attributes,
                                      aid,
                                      error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "aasetup",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Authority.aasetup implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "aasetup",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (pub != NULL)
      g_byte_array_unref (pub);
    if (attributes != NULL)
      g_ptr_array_unref (attributes);
    if (aid != NULL)
      g_free (aid);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
aa_authority_processor_process_aakeygen (aaAuthorityProcessor *self,
                                         gint32 sequence_id,
                                         ThriftProtocol *input_protocol,
                                         ThriftProtocol *output_protocol,
                                         GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  aaAuthorityAakeygenArgs * args =
    g_object_new (AA_TYPE_AUTHORITY_AAKEYGEN_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    aaAuthParamter * auth;
    GByteArray * pub;
    GByteArray * cert;
    GPtrArray * attribtues;
    aaARevoKey * return_value;
    aaAuthorityAakeygenResult * result_struct;

    g_object_get (args,
                  "auth", &auth,
                  "pub", &pub,
                  "cert", &cert,
                  "attribtues", &attribtues,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (AA_TYPE_AUTHORITY_AAKEYGEN_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (aa_authority_handler_aakeygen (AA_AUTHORITY_IF (self->handler),
                                       &return_value,
                                       auth,
                                       pub,
                                       cert,
                                       attribtues,
                                       error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "aakeygen",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Authority.aakeygen implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "aakeygen",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (auth != NULL)
      g_object_unref (auth);
    if (pub != NULL)
      g_byte_array_unref (pub);
    if (cert != NULL)
      g_byte_array_unref (cert);
    if (attribtues != NULL)
      g_ptr_array_unref (attribtues);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
aa_authority_processor_process_updatekey (aaAuthorityProcessor *self,
                                          gint32 sequence_id,
                                          ThriftProtocol *input_protocol,
                                          ThriftProtocol *output_protocol,
                                          GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  aaAuthorityUpdatekeyArgs * args =
    g_object_new (AA_TYPE_AUTHORITY_UPDATEKEY_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * auth_msk;
    GByteArray * pub;
    GByteArray * attr_pk;
    GByteArray * attr_msk;
    gchar * attribute;
    aaAttrPair * return_value;
    aaAuthorityUpdatekeyResult * result_struct;

    g_object_get (args,
                  "auth_msk", &auth_msk,
                  "pub", &pub,
                  "attr_pk", &attr_pk,
                  "attr_msk", &attr_msk,
                  "attribute", &attribute,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (AA_TYPE_AUTHORITY_UPDATEKEY_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (aa_authority_handler_updatekey (AA_AUTHORITY_IF (self->handler),
                                        &return_value,
                                        auth_msk,
                                        pub,
                                        attr_pk,
                                        attr_msk,
                                        attribute,
                                        error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "updatekey",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Authority.updatekey implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "updatekey",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (auth_msk != NULL)
      g_byte_array_unref (auth_msk);
    if (pub != NULL)
      g_byte_array_unref (pub);
    if (attr_pk != NULL)
      g_byte_array_unref (attr_pk);
    if (attr_msk != NULL)
      g_byte_array_unref (attr_msk);
    if (attribute != NULL)
      g_free (attribute);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
aa_authority_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                      ThriftProtocol *input_protocol,
                                      ThriftProtocol *output_protocol,
                                      gchar *method_name,
                                      gint32 sequence_id,
                                      GError **error)
{
  aa_authority_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  aaAuthorityProcessor *self = AA_AUTHORITY_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (AA_AUTHORITY_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    g_free (method_name);
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
aa_authority_processor_set_property (GObject *object,
                                     guint property_id,
                                     const GValue *value,
                                     GParamSpec *pspec)
{
  aaAuthorityProcessor *self = AA_AUTHORITY_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_AA_AUTHORITY_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
aa_authority_processor_get_property (GObject *object,
                                     guint property_id,
                                     GValue *value,
                                     GParamSpec *pspec)
{
  aaAuthorityProcessor *self = AA_AUTHORITY_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_AA_AUTHORITY_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
aa_authority_processor_dispose (GObject *gobject)
{
  aaAuthorityProcessor *self = AA_AUTHORITY_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (aa_authority_processor_parent_class)->dispose (gobject);
}

static void
aa_authority_processor_finalize (GObject *gobject)
{
  aaAuthorityProcessor *self = AA_AUTHORITY_PROCESSOR (gobject);

  thrift_safe_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (aa_authority_processor_parent_class)->finalize (gobject);
}

static void
aa_authority_processor_init (aaAuthorityProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 3; index += 1)
    g_hash_table_insert (self->process_map,
                         aa_authority_processor_process_function_defs[index].name,
                         &aa_authority_processor_process_function_defs[index]);
}

static void
aa_authority_processor_class_init (aaAuthorityProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = aa_authority_processor_dispose;
  gobject_class->finalize = aa_authority_processor_finalize;
  gobject_class->set_property = aa_authority_processor_set_property;
  gobject_class->get_property = aa_authority_processor_get_property;

  dispatch_processor_class->dispatch_call = aa_authority_processor_dispatch_call;
  cls->dispatch_call = aa_authority_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    AA_TYPE_AUTHORITY_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_AA_AUTHORITY_PROCESSOR_HANDLER,
                                   param_spec);
}
