/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CA_CA_TYPES_H
#define CA_CA_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>
/* custom thrift includes */

/* begin types */

/* struct CAParamter */
struct _caCAParamter
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * pub;
  gboolean __isset_pub;
  GByteArray * msk;
  gboolean __isset_msk;
};
typedef struct _caCAParamter caCAParamter;

struct _caCAParamterClass
{
  ThriftStructClass parent;
};
typedef struct _caCAParamterClass caCAParamterClass;

GType ca_c_a_paramter_get_type (void);
#define CA_TYPE_C_A_PARAMTER (ca_c_a_paramter_get_type())
#define CA_C_A_PARAMTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CA_TYPE_C_A_PARAMTER, caCAParamter))
#define CA_C_A_PARAMTER_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), CA__TYPE_C_A_PARAMTER, caCAParamterClass))
#define CA_IS_C_A_PARAMTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CA_TYPE_C_A_PARAMTER))
#define CA_IS_C_A_PARAMTER_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), CA_TYPE_C_A_PARAMTER))
#define CA_C_A_PARAMTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CA_TYPE_C_A_PARAMTER, caCAParamterClass))

/* struct UserRegister */
struct _caUserRegister
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * gpk;
  gboolean __isset_gpk;
  GByteArray * gsk;
  gboolean __isset_gsk;
  GByteArray * UserCert;
  gboolean __isset_UserCert;
  GPtrArray * attributes;
  gboolean __isset_attributes;
  gint32 uid;
  gboolean __isset_uid;
};
typedef struct _caUserRegister caUserRegister;

struct _caUserRegisterClass
{
  ThriftStructClass parent;
};
typedef struct _caUserRegisterClass caUserRegisterClass;

GType ca_user_register_get_type (void);
#define CA_TYPE_USER_REGISTER (ca_user_register_get_type())
#define CA_USER_REGISTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CA_TYPE_USER_REGISTER, caUserRegister))
#define CA_USER_REGISTER_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), CA__TYPE_USER_REGISTER, caUserRegisterClass))
#define CA_IS_USER_REGISTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CA_TYPE_USER_REGISTER))
#define CA_IS_USER_REGISTER_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), CA_TYPE_USER_REGISTER))
#define CA_USER_REGISTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CA_TYPE_USER_REGISTER, caUserRegisterClass))

/* struct URevoKey */
struct _caURevoKey
{ 
  ThriftStruct parent; 

  /* public */
  gint32 m;
  gboolean __isset_m;
  GByteArray * K0;
  gboolean __isset_K0;
  GByteArray * K1;
  gboolean __isset_K1;
  GByteArray * K2;
  gboolean __isset_K2;
  GByteArray * KJ;
  gboolean __isset_KJ;
  GHashTable * Kijx;
  gboolean __isset_Kijx;
  GPtrArray * attributes;
  gboolean __isset_attributes;
};
typedef struct _caURevoKey caURevoKey;

struct _caURevoKeyClass
{
  ThriftStructClass parent;
};
typedef struct _caURevoKeyClass caURevoKeyClass;

GType ca_u_revo_key_get_type (void);
#define CA_TYPE_U_REVO_KEY (ca_u_revo_key_get_type())
#define CA_U_REVO_KEY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CA_TYPE_U_REVO_KEY, caURevoKey))
#define CA_U_REVO_KEY_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), CA__TYPE_U_REVO_KEY, caURevoKeyClass))
#define CA_IS_U_REVO_KEY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CA_TYPE_U_REVO_KEY))
#define CA_IS_U_REVO_KEY_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), CA_TYPE_U_REVO_KEY))
#define CA_U_REVO_KEY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CA_TYPE_U_REVO_KEY, caURevoKeyClass))

/* constants */

/* struct CenterCasetupArgs */
struct _caCenterCasetupArgs
{ 
  ThriftStruct parent; 

  /* public */
  gint32 N;
  gboolean __isset_N;
  gint32 bytesize;
  gboolean __isset_bytesize;
};
typedef struct _caCenterCasetupArgs caCenterCasetupArgs;

struct _caCenterCasetupArgsClass
{
  ThriftStructClass parent;
};
typedef struct _caCenterCasetupArgsClass caCenterCasetupArgsClass;

GType ca_center_casetup_args_get_type (void);
#define CA_TYPE_CENTER_CASETUP_ARGS (ca_center_casetup_args_get_type())
#define CA_CENTER_CASETUP_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CA_TYPE_CENTER_CASETUP_ARGS, caCenterCasetupArgs))
#define CA_CENTER_CASETUP_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), CA__TYPE_CENTER_CASETUP_ARGS, caCenterCasetupArgsClass))
#define CA_IS_CENTER_CASETUP_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CA_TYPE_CENTER_CASETUP_ARGS))
#define CA_IS_CENTER_CASETUP_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), CA_TYPE_CENTER_CASETUP_ARGS))
#define CA_CENTER_CASETUP_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CA_TYPE_CENTER_CASETUP_ARGS, caCenterCasetupArgsClass))

/* struct CenterCasetupResult */
struct _caCenterCasetupResult
{ 
  ThriftStruct parent; 

  /* public */
  caCAParamter * success;
  gboolean __isset_success;
};
typedef struct _caCenterCasetupResult caCenterCasetupResult;

struct _caCenterCasetupResultClass
{
  ThriftStructClass parent;
};
typedef struct _caCenterCasetupResultClass caCenterCasetupResultClass;

GType ca_center_casetup_result_get_type (void);
#define CA_TYPE_CENTER_CASETUP_RESULT (ca_center_casetup_result_get_type())
#define CA_CENTER_CASETUP_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CA_TYPE_CENTER_CASETUP_RESULT, caCenterCasetupResult))
#define CA_CENTER_CASETUP_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), CA__TYPE_CENTER_CASETUP_RESULT, caCenterCasetupResultClass))
#define CA_IS_CENTER_CASETUP_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CA_TYPE_CENTER_CASETUP_RESULT))
#define CA_IS_CENTER_CASETUP_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), CA_TYPE_CENTER_CASETUP_RESULT))
#define CA_CENTER_CASETUP_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CA_TYPE_CENTER_CASETUP_RESULT, caCenterCasetupResultClass))

/* struct CenterUserRegisterArgs */
struct _caCenterUserRegisterArgs
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * pub;
  gboolean __isset_pub;
  gchar * uid;
  gboolean __isset_uid;
  GPtrArray * attributes;
  gboolean __isset_attributes;
};
typedef struct _caCenterUserRegisterArgs caCenterUserRegisterArgs;

struct _caCenterUserRegisterArgsClass
{
  ThriftStructClass parent;
};
typedef struct _caCenterUserRegisterArgsClass caCenterUserRegisterArgsClass;

GType ca_center_user_register_args_get_type (void);
#define CA_TYPE_CENTER_USER_REGISTER_ARGS (ca_center_user_register_args_get_type())
#define CA_CENTER_USER_REGISTER_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CA_TYPE_CENTER_USER_REGISTER_ARGS, caCenterUserRegisterArgs))
#define CA_CENTER_USER_REGISTER_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), CA__TYPE_CENTER_USER_REGISTER_ARGS, caCenterUserRegisterArgsClass))
#define CA_IS_CENTER_USER_REGISTER_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CA_TYPE_CENTER_USER_REGISTER_ARGS))
#define CA_IS_CENTER_USER_REGISTER_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), CA_TYPE_CENTER_USER_REGISTER_ARGS))
#define CA_CENTER_USER_REGISTER_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CA_TYPE_CENTER_USER_REGISTER_ARGS, caCenterUserRegisterArgsClass))

/* struct CenterUserRegisterResult */
struct _caCenterUserRegisterResult
{ 
  ThriftStruct parent; 

  /* public */
  caUserRegister * success;
  gboolean __isset_success;
};
typedef struct _caCenterUserRegisterResult caCenterUserRegisterResult;

struct _caCenterUserRegisterResultClass
{
  ThriftStructClass parent;
};
typedef struct _caCenterUserRegisterResultClass caCenterUserRegisterResultClass;

GType ca_center_user_register_result_get_type (void);
#define CA_TYPE_CENTER_USER_REGISTER_RESULT (ca_center_user_register_result_get_type())
#define CA_CENTER_USER_REGISTER_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CA_TYPE_CENTER_USER_REGISTER_RESULT, caCenterUserRegisterResult))
#define CA_CENTER_USER_REGISTER_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), CA__TYPE_CENTER_USER_REGISTER_RESULT, caCenterUserRegisterResultClass))
#define CA_IS_CENTER_USER_REGISTER_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CA_TYPE_CENTER_USER_REGISTER_RESULT))
#define CA_IS_CENTER_USER_REGISTER_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), CA_TYPE_CENTER_USER_REGISTER_RESULT))
#define CA_CENTER_USER_REGISTER_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CA_TYPE_CENTER_USER_REGISTER_RESULT, caCenterUserRegisterResultClass))

/* struct CenterCakeygenArgs */
struct _caCenterCakeygenArgs
{ 
  ThriftStruct parent; 

  /* public */
  caCAParamter * param;
  gboolean __isset_param;
  GPtrArray * attributes;
  gboolean __isset_attributes;
  gint32 uid;
  gboolean __isset_uid;
};
typedef struct _caCenterCakeygenArgs caCenterCakeygenArgs;

struct _caCenterCakeygenArgsClass
{
  ThriftStructClass parent;
};
typedef struct _caCenterCakeygenArgsClass caCenterCakeygenArgsClass;

GType ca_center_cakeygen_args_get_type (void);
#define CA_TYPE_CENTER_CAKEYGEN_ARGS (ca_center_cakeygen_args_get_type())
#define CA_CENTER_CAKEYGEN_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CA_TYPE_CENTER_CAKEYGEN_ARGS, caCenterCakeygenArgs))
#define CA_CENTER_CAKEYGEN_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), CA__TYPE_CENTER_CAKEYGEN_ARGS, caCenterCakeygenArgsClass))
#define CA_IS_CENTER_CAKEYGEN_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CA_TYPE_CENTER_CAKEYGEN_ARGS))
#define CA_IS_CENTER_CAKEYGEN_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), CA_TYPE_CENTER_CAKEYGEN_ARGS))
#define CA_CENTER_CAKEYGEN_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CA_TYPE_CENTER_CAKEYGEN_ARGS, caCenterCakeygenArgsClass))

/* struct CenterCakeygenResult */
struct _caCenterCakeygenResult
{ 
  ThriftStruct parent; 

  /* public */
  caURevoKey * success;
  gboolean __isset_success;
};
typedef struct _caCenterCakeygenResult caCenterCakeygenResult;

struct _caCenterCakeygenResultClass
{
  ThriftStructClass parent;
};
typedef struct _caCenterCakeygenResultClass caCenterCakeygenResultClass;

GType ca_center_cakeygen_result_get_type (void);
#define CA_TYPE_CENTER_CAKEYGEN_RESULT (ca_center_cakeygen_result_get_type())
#define CA_CENTER_CAKEYGEN_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CA_TYPE_CENTER_CAKEYGEN_RESULT, caCenterCakeygenResult))
#define CA_CENTER_CAKEYGEN_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), CA__TYPE_CENTER_CAKEYGEN_RESULT, caCenterCakeygenResultClass))
#define CA_IS_CENTER_CAKEYGEN_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CA_TYPE_CENTER_CAKEYGEN_RESULT))
#define CA_IS_CENTER_CAKEYGEN_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), CA_TYPE_CENTER_CAKEYGEN_RESULT))
#define CA_CENTER_CAKEYGEN_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CA_TYPE_CENTER_CAKEYGEN_RESULT, caCenterCakeygenResultClass))

#endif /* CA_CA_TYPES_H */
