/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "ca_center.h"

gboolean
ca_center_if_casetup (caCenterIf *iface, caCAParamter ** _return, const gint32 N, const gint32 bytesize, GError **error)
{
  return CA_CENTER_IF_GET_INTERFACE (iface)->casetup (iface, _return, N, bytesize, error);
}

gboolean
ca_center_if_user_register (caCenterIf *iface, caUserRegister ** _return, const GByteArray * pub, const gchar * uid, const GPtrArray * attributes, GError **error)
{
  return CA_CENTER_IF_GET_INTERFACE (iface)->user_register (iface, _return, pub, uid, attributes, error);
}

gboolean
ca_center_if_cakeygen (caCenterIf *iface, caURevoKey ** _return, const caCAParamter * param, const GPtrArray * attributes, const gint32 uid, GError **error)
{
  return CA_CENTER_IF_GET_INTERFACE (iface)->cakeygen (iface, _return, param, attributes, uid, error);
}

GType
ca_center_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (caCenterIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "caCenterIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
ca_center_if_interface_init (caCenterIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (caCenterClient, ca_center_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (CA_TYPE_CENTER_IF,
                                                ca_center_if_interface_init))

enum _caCenterClientProperties
{
  PROP_0,
  PROP_CA_CENTER_CLIENT_INPUT_PROTOCOL,
  PROP_CA_CENTER_CLIENT_OUTPUT_PROTOCOL
};

void
ca_center_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  caCenterClient *client = CA_CENTER_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_CA_CENTER_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_CA_CENTER_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
ca_center_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  caCenterClient *client = CA_CENTER_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_CA_CENTER_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_CA_CENTER_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean ca_center_client_send_casetup (caCenterIf * iface, const gint32 N, const gint32 bytesize, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = CA_CENTER_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "casetup", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "casetup_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "N", T_I32, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, N, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "bytesize", T_I32, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, bytesize, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean ca_center_client_recv_casetup (caCenterIf * iface, caCAParamter ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = CA_CENTER_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "casetup", 7) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected casetup", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean ca_center_client_casetup (caCenterIf * iface, caCAParamter ** _return, const gint32 N, const gint32 bytesize, GError ** error)
{
  if (!ca_center_client_send_casetup (iface, N, bytesize, error))
    return FALSE;
  if (!ca_center_client_recv_casetup (iface, _return, error))
    return FALSE;
  return TRUE;
}

gboolean ca_center_client_send_user_register (caCenterIf * iface, const GByteArray * pub, const gchar * uid, const GPtrArray * attributes, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = CA_CENTER_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "user_register", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "user_register_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "pub", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, pub ? ((GByteArray *) pub)->data : NULL, pub ? ((GByteArray *) pub)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "uid", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, uid, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "attributes", T_LIST, 3, error)) < 0)
      return 0;
    xfer += ret;
    {
      guint i12;

      if ((ret = thrift_protocol_write_list_begin (protocol, T_STRING, (gint32) (attributes ? attributes->len : 0), error)) < 0)
        return 0;
      xfer += ret;
      for (i12 = 0; i12 < (attributes ? attributes->len : 0); i12++)
      {
        if ((ret = thrift_protocol_write_string (protocol, ((gchar*)g_ptr_array_index ((GPtrArray *) attributes, i12)), error)) < 0)
          return 0;
        xfer += ret;

      }
      if ((ret = thrift_protocol_write_list_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean ca_center_client_recv_user_register (caCenterIf * iface, caUserRegister ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = CA_CENTER_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "user_register", 13) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected user_register", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean ca_center_client_user_register (caCenterIf * iface, caUserRegister ** _return, const GByteArray * pub, const gchar * uid, const GPtrArray * attributes, GError ** error)
{
  if (!ca_center_client_send_user_register (iface, pub, uid, attributes, error))
    return FALSE;
  if (!ca_center_client_recv_user_register (iface, _return, error))
    return FALSE;
  return TRUE;
}

gboolean ca_center_client_send_cakeygen (caCenterIf * iface, const caCAParamter * param, const GPtrArray * attributes, const gint32 uid, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = CA_CENTER_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "cakeygen", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "cakeygen_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "param", T_STRUCT, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (param), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "attributes", T_LIST, 2, error)) < 0)
      return 0;
    xfer += ret;
    {
      guint i13;

      if ((ret = thrift_protocol_write_list_begin (protocol, T_STRING, (gint32) (attributes ? attributes->len : 0), error)) < 0)
        return 0;
      xfer += ret;
      for (i13 = 0; i13 < (attributes ? attributes->len : 0); i13++)
      {
        if ((ret = thrift_protocol_write_string (protocol, ((gchar*)g_ptr_array_index ((GPtrArray *) attributes, i13)), error)) < 0)
          return 0;
        xfer += ret;

      }
      if ((ret = thrift_protocol_write_list_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "uid", T_I32, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, uid, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean ca_center_client_recv_cakeygen (caCenterIf * iface, caURevoKey ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = CA_CENTER_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "cakeygen", 8) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected cakeygen", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean ca_center_client_cakeygen (caCenterIf * iface, caURevoKey ** _return, const caCAParamter * param, const GPtrArray * attributes, const gint32 uid, GError ** error)
{
  if (!ca_center_client_send_cakeygen (iface, param, attributes, uid, error))
    return FALSE;
  if (!ca_center_client_recv_cakeygen (iface, _return, error))
    return FALSE;
  return TRUE;
}

static void
ca_center_if_interface_init (caCenterIfInterface *iface)
{
  iface->casetup = ca_center_client_casetup;
  iface->user_register = ca_center_client_user_register;
  iface->cakeygen = ca_center_client_cakeygen;
}

static void
ca_center_client_init (caCenterClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
ca_center_client_class_init (caCenterClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = ca_center_client_set_property;
  gobject_class->get_property = ca_center_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_CA_CENTER_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_CA_CENTER_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
ca_center_handler_center_if_interface_init (caCenterIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (caCenterHandler, 
                         ca_center_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (CA_TYPE_CENTER_IF,
                                                ca_center_handler_center_if_interface_init))

gboolean ca_center_handler_casetup (caCenterIf * iface, caCAParamter ** _return, const gint32 N, const gint32 bytesize, GError ** error)
{
  g_return_val_if_fail (CA_IS_CENTER_HANDLER (iface), FALSE);

  return CA_CENTER_HANDLER_GET_CLASS (iface)->casetup (iface, _return, N, bytesize, error);
}

gboolean ca_center_handler_user_register (caCenterIf * iface, caUserRegister ** _return, const GByteArray * pub, const gchar * uid, const GPtrArray * attributes, GError ** error)
{
  g_return_val_if_fail (CA_IS_CENTER_HANDLER (iface), FALSE);

  return CA_CENTER_HANDLER_GET_CLASS (iface)->user_register (iface, _return, pub, uid, attributes, error);
}

gboolean ca_center_handler_cakeygen (caCenterIf * iface, caURevoKey ** _return, const caCAParamter * param, const GPtrArray * attributes, const gint32 uid, GError ** error)
{
  g_return_val_if_fail (CA_IS_CENTER_HANDLER (iface), FALSE);

  return CA_CENTER_HANDLER_GET_CLASS (iface)->cakeygen (iface, _return, param, attributes, uid, error);
}

static void
ca_center_handler_center_if_interface_init (caCenterIfInterface *iface)
{
  iface->casetup = ca_center_handler_casetup;
  iface->user_register = ca_center_handler_user_register;
  iface->cakeygen = ca_center_handler_cakeygen;
}

static void
ca_center_handler_init (caCenterHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
ca_center_handler_class_init (caCenterHandlerClass *cls)
{
  cls->casetup = NULL;
  cls->user_register = NULL;
  cls->cakeygen = NULL;
}

enum _caCenterProcessorProperties
{
  PROP_CA_CENTER_PROCESSOR_0,
  PROP_CA_CENTER_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (caCenterProcessor,
               ca_center_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* caCenterProcessorProcessFunction) (caCenterProcessor *, 
                                                       gint32,
                                                       ThriftProtocol *,
                                                       ThriftProtocol *,
                                                       GError **);

typedef struct
{
  gchar *name;
  caCenterProcessorProcessFunction function;
} ca_center_processor_process_function_def;

static gboolean
ca_center_processor_process_casetup (caCenterProcessor *,
                                     gint32,
                                     ThriftProtocol *,
                                     ThriftProtocol *,
                                     GError **);
static gboolean
ca_center_processor_process_user_register (caCenterProcessor *,
                                           gint32,
                                           ThriftProtocol *,
                                           ThriftProtocol *,
                                           GError **);
static gboolean
ca_center_processor_process_cakeygen (caCenterProcessor *,
                                      gint32,
                                      ThriftProtocol *,
                                      ThriftProtocol *,
                                      GError **);

static ca_center_processor_process_function_def
ca_center_processor_process_function_defs[3] = {
  {
    "casetup",
    ca_center_processor_process_casetup
  },
  {
    "user_register",
    ca_center_processor_process_user_register
  },
  {
    "cakeygen",
    ca_center_processor_process_cakeygen
  }
};

static gboolean
ca_center_processor_process_casetup (caCenterProcessor *self,
                                     gint32 sequence_id,
                                     ThriftProtocol *input_protocol,
                                     ThriftProtocol *output_protocol,
                                     GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  caCenterCasetupArgs * args =
    g_object_new (CA_TYPE_CENTER_CASETUP_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gint N;
    gint bytesize;
    caCAParamter * return_value;
    caCenterCasetupResult * result_struct;

    g_object_get (args,
                  "N", &N,
                  "bytesize", &bytesize,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (CA_TYPE_CENTER_CASETUP_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (ca_center_handler_casetup (CA_CENTER_IF (self->handler),
                                   &return_value,
                                   N,
                                   bytesize,
                                   error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "casetup",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Center.casetup implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "casetup",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
ca_center_processor_process_user_register (caCenterProcessor *self,
                                           gint32 sequence_id,
                                           ThriftProtocol *input_protocol,
                                           ThriftProtocol *output_protocol,
                                           GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  caCenterUserRegisterArgs * args =
    g_object_new (CA_TYPE_CENTER_USER_REGISTER_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * pub;
    gchar * uid;
    GPtrArray * attributes;
    caUserRegister * return_value;
    caCenterUserRegisterResult * result_struct;

    g_object_get (args,
                  "pub", &pub,
                  "uid", &uid,
                  "attributes", &attributes,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (CA_TYPE_CENTER_USER_REGISTER_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (ca_center_handler_user_register (CA_CENTER_IF (self->handler),
                                         &return_value,
                                         pub,
                                         uid,
                                         attributes,
                                         error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "user_register",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Center.user_register implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "user_register",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (pub != NULL)
      g_byte_array_unref (pub);
    if (uid != NULL)
      g_free (uid);
    if (attributes != NULL)
      g_ptr_array_unref (attributes);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
ca_center_processor_process_cakeygen (caCenterProcessor *self,
                                      gint32 sequence_id,
                                      ThriftProtocol *input_protocol,
                                      ThriftProtocol *output_protocol,
                                      GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  caCenterCakeygenArgs * args =
    g_object_new (CA_TYPE_CENTER_CAKEYGEN_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    caCAParamter * param;
    GPtrArray * attributes;
    gint uid;
    caURevoKey * return_value;
    caCenterCakeygenResult * result_struct;

    g_object_get (args,
                  "param", &param,
                  "attributes", &attributes,
                  "uid", &uid,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (CA_TYPE_CENTER_CAKEYGEN_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (ca_center_handler_cakeygen (CA_CENTER_IF (self->handler),
                                    &return_value,
                                    param,
                                    attributes,
                                    uid,
                                    error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "cakeygen",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Center.cakeygen implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "cakeygen",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (param != NULL)
      g_object_unref (param);
    if (attributes != NULL)
      g_ptr_array_unref (attributes);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
ca_center_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                   ThriftProtocol *input_protocol,
                                   ThriftProtocol *output_protocol,
                                   gchar *method_name,
                                   gint32 sequence_id,
                                   GError **error)
{
  ca_center_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  caCenterProcessor *self = CA_CENTER_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (CA_CENTER_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    g_free (method_name);
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
ca_center_processor_set_property (GObject *object,
                                  guint property_id,
                                  const GValue *value,
                                  GParamSpec *pspec)
{
  caCenterProcessor *self = CA_CENTER_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_CA_CENTER_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
ca_center_processor_get_property (GObject *object,
                                  guint property_id,
                                  GValue *value,
                                  GParamSpec *pspec)
{
  caCenterProcessor *self = CA_CENTER_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_CA_CENTER_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
ca_center_processor_dispose (GObject *gobject)
{
  caCenterProcessor *self = CA_CENTER_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (ca_center_processor_parent_class)->dispose (gobject);
}

static void
ca_center_processor_finalize (GObject *gobject)
{
  caCenterProcessor *self = CA_CENTER_PROCESSOR (gobject);

  thrift_safe_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (ca_center_processor_parent_class)->finalize (gobject);
}

static void
ca_center_processor_init (caCenterProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 3; index += 1)
    g_hash_table_insert (self->process_map,
                         ca_center_processor_process_function_defs[index].name,
                         &ca_center_processor_process_function_defs[index]);
}

static void
ca_center_processor_class_init (caCenterProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = ca_center_processor_dispose;
  gobject_class->finalize = ca_center_processor_finalize;
  gobject_class->set_property = ca_center_processor_set_property;
  gobject_class->get_property = ca_center_processor_get_property;

  dispatch_processor_class->dispatch_call = ca_center_processor_dispatch_call;
  cls->dispatch_call = ca_center_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    CA_TYPE_CENTER_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_CA_CENTER_PROCESSOR_HANDLER,
                                   param_spec);
}
