/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "cloud_cloud.h"

gboolean
cloud_cloud_if_updatecph (cloudCloudIf *iface, GByteArray ** _return, const GByteArray * cph, const GByteArray * pub, const GByteArray * cuk, const gint32 version, const gchar * attribute, GError **error)
{
  return CLOUD_CLOUD_IF_GET_INTERFACE (iface)->updatecph (iface, _return, cph, pub, cuk, version, attribute, error);
}

GType
cloud_cloud_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (cloudCloudIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "cloudCloudIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
cloud_cloud_if_interface_init (cloudCloudIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (cloudCloudClient, cloud_cloud_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (CLOUD_TYPE_CLOUD_IF,
                                                cloud_cloud_if_interface_init))

enum _cloudCloudClientProperties
{
  PROP_0,
  PROP_CLOUD_CLOUD_CLIENT_INPUT_PROTOCOL,
  PROP_CLOUD_CLOUD_CLIENT_OUTPUT_PROTOCOL
};

void
cloud_cloud_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  cloudCloudClient *client = CLOUD_CLOUD_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_CLOUD_CLOUD_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_CLOUD_CLOUD_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
cloud_cloud_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  cloudCloudClient *client = CLOUD_CLOUD_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_CLOUD_CLOUD_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_CLOUD_CLOUD_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean cloud_cloud_client_send_updatecph (cloudCloudIf * iface, const GByteArray * cph, const GByteArray * pub, const GByteArray * cuk, const gint32 version, const gchar * attribute, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = CLOUD_CLOUD_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "updatecph", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "updatecph_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "cph", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, cph ? ((GByteArray *) cph)->data : NULL, cph ? ((GByteArray *) cph)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "pub", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, pub ? ((GByteArray *) pub)->data : NULL, pub ? ((GByteArray *) pub)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "cuk", T_STRING, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, cuk ? ((GByteArray *) cuk)->data : NULL, cuk ? ((GByteArray *) cuk)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "version", T_I32, 4, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, version, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "attribute", T_STRING, 5, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, attribute, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean cloud_cloud_client_recv_updatecph (cloudCloudIf * iface, GByteArray ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = CLOUD_CLOUD_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "updatecph", 9) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected updatecph", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRING)
          {
            if (*_return != NULL)
            {
              g_free(*_return);
              *_return = NULL;
            }

            if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
              return 0;
            xfer += ret;
            *_return = g_byte_array_new();
            g_byte_array_append (*_return, (guint8 *) data, (guint) len);
            g_free (data);
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean cloud_cloud_client_updatecph (cloudCloudIf * iface, GByteArray ** _return, const GByteArray * cph, const GByteArray * pub, const GByteArray * cuk, const gint32 version, const gchar * attribute, GError ** error)
{
  if (!cloud_cloud_client_send_updatecph (iface, cph, pub, cuk, version, attribute, error))
    return FALSE;
  if (!cloud_cloud_client_recv_updatecph (iface, _return, error))
    return FALSE;
  return TRUE;
}

static void
cloud_cloud_if_interface_init (cloudCloudIfInterface *iface)
{
  iface->updatecph = cloud_cloud_client_updatecph;
}

static void
cloud_cloud_client_init (cloudCloudClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
cloud_cloud_client_class_init (cloudCloudClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = cloud_cloud_client_set_property;
  gobject_class->get_property = cloud_cloud_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_CLOUD_CLOUD_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_CLOUD_CLOUD_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
cloud_cloud_handler_cloud_if_interface_init (cloudCloudIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (cloudCloudHandler, 
                         cloud_cloud_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (CLOUD_TYPE_CLOUD_IF,
                                                cloud_cloud_handler_cloud_if_interface_init))

gboolean cloud_cloud_handler_updatecph (cloudCloudIf * iface, GByteArray ** _return, const GByteArray * cph, const GByteArray * pub, const GByteArray * cuk, const gint32 version, const gchar * attribute, GError ** error)
{
  g_return_val_if_fail (CLOUD_IS_CLOUD_HANDLER (iface), FALSE);

  return CLOUD_CLOUD_HANDLER_GET_CLASS (iface)->updatecph (iface, _return, cph, pub, cuk, version, attribute, error);
}

static void
cloud_cloud_handler_cloud_if_interface_init (cloudCloudIfInterface *iface)
{
  iface->updatecph = cloud_cloud_handler_updatecph;
}

static void
cloud_cloud_handler_init (cloudCloudHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
cloud_cloud_handler_class_init (cloudCloudHandlerClass *cls)
{
  cls->updatecph = NULL;
}

enum _cloudCloudProcessorProperties
{
  PROP_CLOUD_CLOUD_PROCESSOR_0,
  PROP_CLOUD_CLOUD_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (cloudCloudProcessor,
               cloud_cloud_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* cloudCloudProcessorProcessFunction) (cloudCloudProcessor *, 
                                                         gint32,
                                                         ThriftProtocol *,
                                                         ThriftProtocol *,
                                                         GError **);

typedef struct
{
  gchar *name;
  cloudCloudProcessorProcessFunction function;
} cloud_cloud_processor_process_function_def;

static gboolean
cloud_cloud_processor_process_updatecph (cloudCloudProcessor *,
                                         gint32,
                                         ThriftProtocol *,
                                         ThriftProtocol *,
                                         GError **);

static cloud_cloud_processor_process_function_def
cloud_cloud_processor_process_function_defs[1] = {
  {
    "updatecph",
    cloud_cloud_processor_process_updatecph
  }
};

static gboolean
cloud_cloud_processor_process_updatecph (cloudCloudProcessor *self,
                                         gint32 sequence_id,
                                         ThriftProtocol *input_protocol,
                                         ThriftProtocol *output_protocol,
                                         GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  cloudCloudUpdatecphArgs * args =
    g_object_new (CLOUD_TYPE_CLOUD_UPDATECPH_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * cph;
    GByteArray * pub;
    GByteArray * cuk;
    gint version;
    gchar * attribute;
    GByteArray * return_value;
    cloudCloudUpdatecphResult * result_struct;

    g_object_get (args,
                  "cph", &cph,
                  "pub", &pub,
                  "cuk", &cuk,
                  "version", &version,
                  "attribute", &attribute,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (CLOUD_TYPE_CLOUD_UPDATECPH_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (cloud_cloud_handler_updatecph (CLOUD_CLOUD_IF (self->handler),
                                       &return_value,
                                       cph,
                                       pub,
                                       cuk,
                                       version,
                                       attribute,
                                       error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_byte_array_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "updatecph",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Cloud.updatecph implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "updatecph",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (cph != NULL)
      g_byte_array_unref (cph);
    if (pub != NULL)
      g_byte_array_unref (pub);
    if (cuk != NULL)
      g_byte_array_unref (cuk);
    if (attribute != NULL)
      g_free (attribute);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
cloud_cloud_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                     ThriftProtocol *input_protocol,
                                     ThriftProtocol *output_protocol,
                                     gchar *method_name,
                                     gint32 sequence_id,
                                     GError **error)
{
  cloud_cloud_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  cloudCloudProcessor *self = CLOUD_CLOUD_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (CLOUD_CLOUD_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    g_free (method_name);
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
cloud_cloud_processor_set_property (GObject *object,
                                    guint property_id,
                                    const GValue *value,
                                    GParamSpec *pspec)
{
  cloudCloudProcessor *self = CLOUD_CLOUD_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_CLOUD_CLOUD_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
cloud_cloud_processor_get_property (GObject *object,
                                    guint property_id,
                                    GValue *value,
                                    GParamSpec *pspec)
{
  cloudCloudProcessor *self = CLOUD_CLOUD_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_CLOUD_CLOUD_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
cloud_cloud_processor_dispose (GObject *gobject)
{
  cloudCloudProcessor *self = CLOUD_CLOUD_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (cloud_cloud_processor_parent_class)->dispose (gobject);
}

static void
cloud_cloud_processor_finalize (GObject *gobject)
{
  cloudCloudProcessor *self = CLOUD_CLOUD_PROCESSOR (gobject);

  thrift_safe_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (cloud_cloud_processor_parent_class)->finalize (gobject);
}

static void
cloud_cloud_processor_init (cloudCloudProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 1; index += 1)
    g_hash_table_insert (self->process_map,
                         cloud_cloud_processor_process_function_defs[index].name,
                         &cloud_cloud_processor_process_function_defs[index]);
}

static void
cloud_cloud_processor_class_init (cloudCloudProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = cloud_cloud_processor_dispose;
  gobject_class->finalize = cloud_cloud_processor_finalize;
  gobject_class->set_property = cloud_cloud_processor_set_property;
  gobject_class->get_property = cloud_cloud_processor_get_property;

  dispatch_processor_class->dispatch_call = cloud_cloud_processor_dispatch_call;
  cls->dispatch_call = cloud_cloud_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    CLOUD_TYPE_CLOUD_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_CLOUD_CLOUD_PROCESSOR_HANDLER,
                                   param_spec);
}
