/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include <math.h>

#include "cloud_cloud_types.h"
#include <thrift/c_glib/thrift.h>

/* constants */

enum _cloudCloudUpdatecphArgsProperties
{
  PROP_CLOUD_CLOUD_UPDATECPH_ARGS_0,
  PROP_CLOUD_CLOUD_UPDATECPH_ARGS_CPH,
  PROP_CLOUD_CLOUD_UPDATECPH_ARGS_PUB,
  PROP_CLOUD_CLOUD_UPDATECPH_ARGS_CUK,
  PROP_CLOUD_CLOUD_UPDATECPH_ARGS_VERSION,
  PROP_CLOUD_CLOUD_UPDATECPH_ARGS_ATTRIBUTE
};

/* reads a cloud_updatecph_args object */
static gint32
cloud_cloud_updatecph_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  cloudCloudUpdatecphArgs * this_object = CLOUD_CLOUD_UPDATECPH_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_STRING)
        {
          if (this_object->cph != NULL)
          {
            g_free(this_object->cph);
            this_object->cph = NULL;
          }

          if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
            return -1;
          xfer += ret;
          this_object->cph = g_byte_array_new();
          g_byte_array_append (this_object->cph, (guint8 *) data, (guint) len);
          g_free (data);
          this_object->__isset_cph = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 2:
        if (ftype == T_STRING)
        {
          if (this_object->pub != NULL)
          {
            g_free(this_object->pub);
            this_object->pub = NULL;
          }

          if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
            return -1;
          xfer += ret;
          this_object->pub = g_byte_array_new();
          g_byte_array_append (this_object->pub, (guint8 *) data, (guint) len);
          g_free (data);
          this_object->__isset_pub = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 3:
        if (ftype == T_STRING)
        {
          if (this_object->cuk != NULL)
          {
            g_free(this_object->cuk);
            this_object->cuk = NULL;
          }

          if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
            return -1;
          xfer += ret;
          this_object->cuk = g_byte_array_new();
          g_byte_array_append (this_object->cuk, (guint8 *) data, (guint) len);
          g_free (data);
          this_object->__isset_cuk = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 4:
        if (ftype == T_I32)
        {
          if ((ret = thrift_protocol_read_i32 (protocol, &this_object->version, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_version = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 5:
        if (ftype == T_STRING)
        {
          if (this_object->attribute != NULL)
          {
            g_free(this_object->attribute);
            this_object->attribute = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->attribute, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_attribute = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
cloud_cloud_updatecph_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  cloudCloudUpdatecphArgs * this_object = CLOUD_CLOUD_UPDATECPH_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "CloudUpdatecphArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "cph", T_STRING, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_binary (protocol, this_object->cph ? ((GByteArray *) this_object->cph)->data : NULL, this_object->cph ? ((GByteArray *) this_object->cph)->len : 0, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "pub", T_STRING, 2, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_binary (protocol, this_object->pub ? ((GByteArray *) this_object->pub)->data : NULL, this_object->pub ? ((GByteArray *) this_object->pub)->len : 0, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "cuk", T_STRING, 3, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_binary (protocol, this_object->cuk ? ((GByteArray *) this_object->cuk)->data : NULL, this_object->cuk ? ((GByteArray *) this_object->cuk)->len : 0, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "version", T_I32, 4, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i32 (protocol, this_object->version, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "attribute", T_STRING, 5, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->attribute, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
cloud_cloud_updatecph_args_set_property (GObject *object,
                                         guint property_id,
                                         const GValue *value,
                                         GParamSpec *pspec)
{
  cloudCloudUpdatecphArgs *self = CLOUD_CLOUD_UPDATECPH_ARGS (object);

  switch (property_id)
  {
    case PROP_CLOUD_CLOUD_UPDATECPH_ARGS_CPH:
      if (self->cph != NULL)
        g_byte_array_unref (self->cph);
      self->cph = g_value_dup_boxed (value);
      self->__isset_cph = TRUE;
      break;

    case PROP_CLOUD_CLOUD_UPDATECPH_ARGS_PUB:
      if (self->pub != NULL)
        g_byte_array_unref (self->pub);
      self->pub = g_value_dup_boxed (value);
      self->__isset_pub = TRUE;
      break;

    case PROP_CLOUD_CLOUD_UPDATECPH_ARGS_CUK:
      if (self->cuk != NULL)
        g_byte_array_unref (self->cuk);
      self->cuk = g_value_dup_boxed (value);
      self->__isset_cuk = TRUE;
      break;

    case PROP_CLOUD_CLOUD_UPDATECPH_ARGS_VERSION:
      self->version = g_value_get_int (value);
      self->__isset_version = TRUE;
      break;

    case PROP_CLOUD_CLOUD_UPDATECPH_ARGS_ATTRIBUTE:
      if (self->attribute != NULL)
        g_free (self->attribute);
      self->attribute = g_value_dup_string (value);
      self->__isset_attribute = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
cloud_cloud_updatecph_args_get_property (GObject *object,
                                         guint property_id,
                                         GValue *value,
                                         GParamSpec *pspec)
{
  cloudCloudUpdatecphArgs *self = CLOUD_CLOUD_UPDATECPH_ARGS (object);

  switch (property_id)
  {
    case PROP_CLOUD_CLOUD_UPDATECPH_ARGS_CPH:
      g_value_set_boxed (value, self->cph);
      break;

    case PROP_CLOUD_CLOUD_UPDATECPH_ARGS_PUB:
      g_value_set_boxed (value, self->pub);
      break;

    case PROP_CLOUD_CLOUD_UPDATECPH_ARGS_CUK:
      g_value_set_boxed (value, self->cuk);
      break;

    case PROP_CLOUD_CLOUD_UPDATECPH_ARGS_VERSION:
      g_value_set_int (value, self->version);
      break;

    case PROP_CLOUD_CLOUD_UPDATECPH_ARGS_ATTRIBUTE:
      g_value_set_string (value, self->attribute);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
cloud_cloud_updatecph_args_instance_init (cloudCloudUpdatecphArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->cph = NULL;
  object->__isset_cph = FALSE;
  object->pub = NULL;
  object->__isset_pub = FALSE;
  object->cuk = NULL;
  object->__isset_cuk = FALSE;
  object->version = 0;
  object->__isset_version = FALSE;
  object->attribute = NULL;
  object->__isset_attribute = FALSE;
}

static void 
cloud_cloud_updatecph_args_finalize (GObject *object)
{
  cloudCloudUpdatecphArgs *tobject = CLOUD_CLOUD_UPDATECPH_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->cph != NULL)
  {
    thrift_string_free(tobject->cph);
    tobject->cph = NULL;
  }
  if (tobject->pub != NULL)
  {
    thrift_string_free(tobject->pub);
    tobject->pub = NULL;
  }
  if (tobject->cuk != NULL)
  {
    thrift_string_free(tobject->cuk);
    tobject->cuk = NULL;
  }
  if (tobject->attribute != NULL)
  {
    g_free(tobject->attribute);
    tobject->attribute = NULL;
  }
}

static void
cloud_cloud_updatecph_args_class_init (cloudCloudUpdatecphArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = cloud_cloud_updatecph_args_read;
  struct_class->write = cloud_cloud_updatecph_args_write;

  gobject_class->finalize = cloud_cloud_updatecph_args_finalize;
  gobject_class->get_property = cloud_cloud_updatecph_args_get_property;
  gobject_class->set_property = cloud_cloud_updatecph_args_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_CLOUD_CLOUD_UPDATECPH_ARGS_CPH,
     g_param_spec_boxed ("cph",
                         NULL,
                         NULL,
                         G_TYPE_BYTE_ARRAY,
                         G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_CLOUD_CLOUD_UPDATECPH_ARGS_PUB,
     g_param_spec_boxed ("pub",
                         NULL,
                         NULL,
                         G_TYPE_BYTE_ARRAY,
                         G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_CLOUD_CLOUD_UPDATECPH_ARGS_CUK,
     g_param_spec_boxed ("cuk",
                         NULL,
                         NULL,
                         G_TYPE_BYTE_ARRAY,
                         G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_CLOUD_CLOUD_UPDATECPH_ARGS_VERSION,
     g_param_spec_int ("version",
                       NULL,
                       NULL,
                       G_MININT32,
                       G_MAXINT32,
                       0,
                       G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_CLOUD_CLOUD_UPDATECPH_ARGS_ATTRIBUTE,
     g_param_spec_string ("attribute",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));
}

GType
cloud_cloud_updatecph_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (cloudCloudUpdatecphArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) cloud_cloud_updatecph_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (cloudCloudUpdatecphArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) cloud_cloud_updatecph_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "cloudCloudUpdatecphArgsType",
                                   &type_info, 0);
  }

  return type;
}

enum _cloudCloudUpdatecphResultProperties
{
  PROP_CLOUD_CLOUD_UPDATECPH_RESULT_0,
  PROP_CLOUD_CLOUD_UPDATECPH_RESULT_SUCCESS
};

/* reads a cloud_updatecph_result object */
static gint32
cloud_cloud_updatecph_result_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  cloudCloudUpdatecphResult * this_object = CLOUD_CLOUD_UPDATECPH_RESULT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 0:
        if (ftype == T_STRING)
        {
          if (this_object->success != NULL)
          {
            g_free(this_object->success);
            this_object->success = NULL;
          }

          if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
            return -1;
          xfer += ret;
          this_object->success = g_byte_array_new();
          g_byte_array_append (this_object->success, (guint8 *) data, (guint) len);
          g_free (data);
          this_object->__isset_success = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
cloud_cloud_updatecph_result_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  cloudCloudUpdatecphResult * this_object = CLOUD_CLOUD_UPDATECPH_RESULT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "CloudUpdatecphResult", error)) < 0)
    return -1;
  xfer += ret;
  if (this_object->__isset_success == TRUE) {
    if ((ret = thrift_protocol_write_field_begin (protocol, "success", T_STRING, 0, error)) < 0)
      return -1;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, this_object->success ? ((GByteArray *) this_object->success)->data : NULL, this_object->success ? ((GByteArray *) this_object->success)->len : 0, error)) < 0)
      return -1;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
cloud_cloud_updatecph_result_set_property (GObject *object,
                                           guint property_id,
                                           const GValue *value,
                                           GParamSpec *pspec)
{
  cloudCloudUpdatecphResult *self = CLOUD_CLOUD_UPDATECPH_RESULT (object);

  switch (property_id)
  {
    case PROP_CLOUD_CLOUD_UPDATECPH_RESULT_SUCCESS:
      if (self->success != NULL)
        g_byte_array_unref (self->success);
      self->success = g_value_dup_boxed (value);
      self->__isset_success = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
cloud_cloud_updatecph_result_get_property (GObject *object,
                                           guint property_id,
                                           GValue *value,
                                           GParamSpec *pspec)
{
  cloudCloudUpdatecphResult *self = CLOUD_CLOUD_UPDATECPH_RESULT (object);

  switch (property_id)
  {
    case PROP_CLOUD_CLOUD_UPDATECPH_RESULT_SUCCESS:
      g_value_set_boxed (value, self->success);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
cloud_cloud_updatecph_result_instance_init (cloudCloudUpdatecphResult * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->success = NULL;
  object->__isset_success = FALSE;
}

static void 
cloud_cloud_updatecph_result_finalize (GObject *object)
{
  cloudCloudUpdatecphResult *tobject = CLOUD_CLOUD_UPDATECPH_RESULT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->success != NULL)
  {
    thrift_string_free(tobject->success);
    tobject->success = NULL;
  }
}

static void
cloud_cloud_updatecph_result_class_init (cloudCloudUpdatecphResultClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = cloud_cloud_updatecph_result_read;
  struct_class->write = cloud_cloud_updatecph_result_write;

  gobject_class->finalize = cloud_cloud_updatecph_result_finalize;
  gobject_class->get_property = cloud_cloud_updatecph_result_get_property;
  gobject_class->set_property = cloud_cloud_updatecph_result_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_CLOUD_CLOUD_UPDATECPH_RESULT_SUCCESS,
     g_param_spec_boxed ("success",
                         NULL,
                         NULL,
                         G_TYPE_BYTE_ARRAY,
                         G_PARAM_READWRITE));
}

GType
cloud_cloud_updatecph_result_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (cloudCloudUpdatecphResultClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) cloud_cloud_updatecph_result_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (cloudCloudUpdatecphResult),
      0, /* n_preallocs */
      (GInstanceInitFunc) cloud_cloud_updatecph_result_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "cloudCloudUpdatecphResultType",
                                   &type_info, 0);
  }

  return type;
}

