/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "user_user.h"

gboolean
user_user_if_encrypt (userUserIf *iface, GByteArray ** _return, const GByteArray * pub, const GPtrArray * attr_pks, const gchar * policy, const GArray * revo_list, const gint32 uindex, const GByteArray * mes, GError **error)
{
  return USER_USER_IF_GET_INTERFACE (iface)->encrypt (iface, _return, pub, attr_pks, policy, revo_list, uindex, mes, error);
}

gboolean
user_user_if_decrypt (userUserIf *iface, GByteArray ** _return, const GByteArray * cph, const GByteArray * pub, const userUserPrvKey * prv, GError **error)
{
  return USER_USER_IF_GET_INTERFACE (iface)->decrypt (iface, _return, cph, pub, prv, error);
}

GType
user_user_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (userUserIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "userUserIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
user_user_if_interface_init (userUserIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (userUserClient, user_user_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (USER_TYPE_USER_IF,
                                                user_user_if_interface_init))

enum _userUserClientProperties
{
  PROP_0,
  PROP_USER_USER_CLIENT_INPUT_PROTOCOL,
  PROP_USER_USER_CLIENT_OUTPUT_PROTOCOL
};

void
user_user_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  userUserClient *client = USER_USER_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_USER_USER_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_USER_USER_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
user_user_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  userUserClient *client = USER_USER_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_USER_USER_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_USER_USER_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean user_user_client_send_encrypt (userUserIf * iface, const GByteArray * pub, const GPtrArray * attr_pks, const gchar * policy, const GArray * revo_list, const gint32 uindex, const GByteArray * mes, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = USER_USER_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "encrypt", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "encrypt_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "pub", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, pub ? ((GByteArray *) pub)->data : NULL, pub ? ((GByteArray *) pub)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "attr_pks", T_LIST, 2, error)) < 0)
      return 0;
    xfer += ret;
    {
      guint i18;

      if ((ret = thrift_protocol_write_list_begin (protocol, T_STRUCT, (gint32) (attr_pks ? attr_pks->len : 0), error)) < 0)
        return 0;
      xfer += ret;
      for (i18 = 0; i18 < (attr_pks ? attr_pks->len : 0); i18++)
      {
        if ((ret = thrift_struct_write (THRIFT_STRUCT ((g_ptr_array_index ((GPtrArray *) attr_pks, i18))), protocol, error)) < 0)
          return 0;
        xfer += ret;

      }
      if ((ret = thrift_protocol_write_list_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "policy", T_STRING, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, policy, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "revo_list", T_LIST, 4, error)) < 0)
      return 0;
    xfer += ret;
    {
      guint i19;

      if ((ret = thrift_protocol_write_list_begin (protocol, T_I32, (gint32) (revo_list ? revo_list->len : 0), error)) < 0)
        return 0;
      xfer += ret;
      for (i19 = 0; i19 < (revo_list ? revo_list->len : 0); i19++)
      {
        if ((ret = thrift_protocol_write_i32 (protocol, (g_array_index (revo_list, gint32, i19)), error)) < 0)
          return 0;
        xfer += ret;

      }
      if ((ret = thrift_protocol_write_list_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "uindex", T_I32, 5, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, uindex, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "mes", T_STRING, 6, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, mes ? ((GByteArray *) mes)->data : NULL, mes ? ((GByteArray *) mes)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean user_user_client_recv_encrypt (userUserIf * iface, GByteArray ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = USER_USER_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "encrypt", 7) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected encrypt", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRING)
          {
            if (*_return != NULL)
            {
              g_free(*_return);
              *_return = NULL;
            }

            if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
              return 0;
            xfer += ret;
            *_return = g_byte_array_new();
            g_byte_array_append (*_return, (guint8 *) data, (guint) len);
            g_free (data);
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean user_user_client_encrypt (userUserIf * iface, GByteArray ** _return, const GByteArray * pub, const GPtrArray * attr_pks, const gchar * policy, const GArray * revo_list, const gint32 uindex, const GByteArray * mes, GError ** error)
{
  if (!user_user_client_send_encrypt (iface, pub, attr_pks, policy, revo_list, uindex, mes, error))
    return FALSE;
  if (!user_user_client_recv_encrypt (iface, _return, error))
    return FALSE;
  return TRUE;
}

gboolean user_user_client_send_decrypt (userUserIf * iface, const GByteArray * cph, const GByteArray * pub, const userUserPrvKey * prv, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = USER_USER_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "decrypt", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "decrypt_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "cph", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, cph ? ((GByteArray *) cph)->data : NULL, cph ? ((GByteArray *) cph)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "pub", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, pub ? ((GByteArray *) pub)->data : NULL, pub ? ((GByteArray *) pub)->len : 0, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "prv", T_STRUCT, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (prv), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean user_user_client_recv_decrypt (userUserIf * iface, GByteArray ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = USER_USER_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "decrypt", 7) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected decrypt", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRING)
          {
            if (*_return != NULL)
            {
              g_free(*_return);
              *_return = NULL;
            }

            if ((ret = thrift_protocol_read_binary (protocol, &data, &len, error)) < 0)
              return 0;
            xfer += ret;
            *_return = g_byte_array_new();
            g_byte_array_append (*_return, (guint8 *) data, (guint) len);
            g_free (data);
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean user_user_client_decrypt (userUserIf * iface, GByteArray ** _return, const GByteArray * cph, const GByteArray * pub, const userUserPrvKey * prv, GError ** error)
{
  if (!user_user_client_send_decrypt (iface, cph, pub, prv, error))
    return FALSE;
  if (!user_user_client_recv_decrypt (iface, _return, error))
    return FALSE;
  return TRUE;
}

static void
user_user_if_interface_init (userUserIfInterface *iface)
{
  iface->encrypt = user_user_client_encrypt;
  iface->decrypt = user_user_client_decrypt;
}

static void
user_user_client_init (userUserClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
user_user_client_class_init (userUserClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = user_user_client_set_property;
  gobject_class->get_property = user_user_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_USER_USER_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_USER_USER_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
user_user_handler_user_if_interface_init (userUserIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (userUserHandler, 
                         user_user_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (USER_TYPE_USER_IF,
                                                user_user_handler_user_if_interface_init))

gboolean user_user_handler_encrypt (userUserIf * iface, GByteArray ** _return, const GByteArray * pub, const GPtrArray * attr_pks, const gchar * policy, const GArray * revo_list, const gint32 uindex, const GByteArray * mes, GError ** error)
{
  g_return_val_if_fail (USER_IS_USER_HANDLER (iface), FALSE);

  return USER_USER_HANDLER_GET_CLASS (iface)->encrypt (iface, _return, pub, attr_pks, policy, revo_list, uindex, mes, error);
}

gboolean user_user_handler_decrypt (userUserIf * iface, GByteArray ** _return, const GByteArray * cph, const GByteArray * pub, const userUserPrvKey * prv, GError ** error)
{
  g_return_val_if_fail (USER_IS_USER_HANDLER (iface), FALSE);

  return USER_USER_HANDLER_GET_CLASS (iface)->decrypt (iface, _return, cph, pub, prv, error);
}

static void
user_user_handler_user_if_interface_init (userUserIfInterface *iface)
{
  iface->encrypt = user_user_handler_encrypt;
  iface->decrypt = user_user_handler_decrypt;
}

static void
user_user_handler_init (userUserHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
user_user_handler_class_init (userUserHandlerClass *cls)
{
  cls->encrypt = NULL;
  cls->decrypt = NULL;
}

enum _userUserProcessorProperties
{
  PROP_USER_USER_PROCESSOR_0,
  PROP_USER_USER_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (userUserProcessor,
               user_user_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* userUserProcessorProcessFunction) (userUserProcessor *, 
                                                       gint32,
                                                       ThriftProtocol *,
                                                       ThriftProtocol *,
                                                       GError **);

typedef struct
{
  gchar *name;
  userUserProcessorProcessFunction function;
} user_user_processor_process_function_def;

static gboolean
user_user_processor_process_encrypt (userUserProcessor *,
                                     gint32,
                                     ThriftProtocol *,
                                     ThriftProtocol *,
                                     GError **);
static gboolean
user_user_processor_process_decrypt (userUserProcessor *,
                                     gint32,
                                     ThriftProtocol *,
                                     ThriftProtocol *,
                                     GError **);

static user_user_processor_process_function_def
user_user_processor_process_function_defs[2] = {
  {
    "encrypt",
    user_user_processor_process_encrypt
  },
  {
    "decrypt",
    user_user_processor_process_decrypt
  }
};

static gboolean
user_user_processor_process_encrypt (userUserProcessor *self,
                                     gint32 sequence_id,
                                     ThriftProtocol *input_protocol,
                                     ThriftProtocol *output_protocol,
                                     GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  userUserEncryptArgs * args =
    g_object_new (USER_TYPE_USER_ENCRYPT_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * pub;
    GPtrArray * attr_pks;
    gchar * policy;
    GArray * revo_list;
    gint uindex;
    GByteArray * mes;
    GByteArray * return_value;
    userUserEncryptResult * result_struct;

    g_object_get (args,
                  "pub", &pub,
                  "attr_pks", &attr_pks,
                  "policy", &policy,
                  "revo_list", &revo_list,
                  "uindex", &uindex,
                  "mes", &mes,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (USER_TYPE_USER_ENCRYPT_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (user_user_handler_encrypt (USER_USER_IF (self->handler),
                                   &return_value,
                                   pub,
                                   attr_pks,
                                   policy,
                                   revo_list,
                                   uindex,
                                   mes,
                                   error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_byte_array_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "encrypt",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("User.encrypt implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "encrypt",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (pub != NULL)
      g_byte_array_unref (pub);
    if (attr_pks != NULL)
      g_ptr_array_unref (attr_pks);
    if (policy != NULL)
      g_free (policy);
    if (revo_list != NULL)
      g_array_unref (revo_list);
    if (mes != NULL)
      g_byte_array_unref (mes);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
user_user_processor_process_decrypt (userUserProcessor *self,
                                     gint32 sequence_id,
                                     ThriftProtocol *input_protocol,
                                     ThriftProtocol *output_protocol,
                                     GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  userUserDecryptArgs * args =
    g_object_new (USER_TYPE_USER_DECRYPT_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    GByteArray * cph;
    GByteArray * pub;
    userUserPrvKey * prv;
    GByteArray * return_value;
    userUserDecryptResult * result_struct;

    g_object_get (args,
                  "cph", &cph,
                  "pub", &pub,
                  "prv", &prv,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (USER_TYPE_USER_DECRYPT_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (user_user_handler_decrypt (USER_USER_IF (self->handler),
                                   &return_value,
                                   cph,
                                   pub,
                                   prv,
                                   error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_byte_array_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "decrypt",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("User.decrypt implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "decrypt",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (cph != NULL)
      g_byte_array_unref (cph);
    if (pub != NULL)
      g_byte_array_unref (pub);
    if (prv != NULL)
      g_object_unref (prv);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
user_user_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                   ThriftProtocol *input_protocol,
                                   ThriftProtocol *output_protocol,
                                   gchar *method_name,
                                   gint32 sequence_id,
                                   GError **error)
{
  user_user_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  userUserProcessor *self = USER_USER_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (USER_USER_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    g_free (method_name);
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
user_user_processor_set_property (GObject *object,
                                  guint property_id,
                                  const GValue *value,
                                  GParamSpec *pspec)
{
  userUserProcessor *self = USER_USER_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_USER_USER_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
user_user_processor_get_property (GObject *object,
                                  guint property_id,
                                  GValue *value,
                                  GParamSpec *pspec)
{
  userUserProcessor *self = USER_USER_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_USER_USER_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
user_user_processor_dispose (GObject *gobject)
{
  userUserProcessor *self = USER_USER_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (user_user_processor_parent_class)->dispose (gobject);
}

static void
user_user_processor_finalize (GObject *gobject)
{
  userUserProcessor *self = USER_USER_PROCESSOR (gobject);

  thrift_safe_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (user_user_processor_parent_class)->finalize (gobject);
}

static void
user_user_processor_init (userUserProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 2; index += 1)
    g_hash_table_insert (self->process_map,
                         user_user_processor_process_function_defs[index].name,
                         &user_user_processor_process_function_defs[index]);
}

static void
user_user_processor_class_init (userUserProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = user_user_processor_dispose;
  gobject_class->finalize = user_user_processor_finalize;
  gobject_class->set_property = user_user_processor_set_property;
  gobject_class->get_property = user_user_processor_get_property;

  dispatch_processor_class->dispatch_call = user_user_processor_dispatch_call;
  cls->dispatch_call = user_user_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    USER_TYPE_USER_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_USER_USER_PROCESSOR_HANDLER,
                                   param_spec);
}
